[package]
name = "astarte-device-sdk-ffi"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["iot", "astarte", "ffi"]

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
astarte-device-sdk.workspace = true
tokio = { workspace = true, features = [
  # "rt",
  "rt-multi-thread",
  # "signal",
  # "test-util"
] }
eyre.workspace = true
ffi-convert.workspace = true
ffi-convert-derive.workspace = true
url.workspace = true
tracing.workspace = true
# typeshare.workspace = true
