# Top level table specifies Shared Config settings that apply to all backends:
lib-name = "AstarteDeviceLib"

# [kotlin]
# Individual tables can override Shared Config settings:
# lib-name = "LibraryNameOverride"
# Along with backend specific settings:
# domain = "org.myOrganization"

# [demo_gen]
# explicit-generation = true

# [other-library-name]
# some-value = 100
